console.log("Error Handling");
console.log("test-1");
try{
console.log(a);
}
catch(e){
    console.log("Error:",e);
}
console.log("test-2");
console.log("test-3");
